import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ToDos from './ToDos'
import CreateModal from '../components/CreateModal'

import connectToDatabase from '../util/mongodb';

function Home({data}) {
  return (
    <div>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brooke's To Do App
        </h1>
        <button>Add Item</button>
        <CreateModal />
        <ToDos data={data}/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
    const { db } = await connectToDatabase();
    const data = await db
      .collection("to-dos")
      .find()
      .sort({ metacritic: -1 })
      .limit(20)
      .toArray();

    return {
      props: {
        data: JSON.parse(JSON.stringify(data))
      }
    }
  };
 

export default Home





