import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div /* className={styles.container}*/ >
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brooke's To Do App
        </h1>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
